name: .NET

on: [push, pull_request]

jobs:
  build:

    runs-on: self-hosted
    env:
       DOTNET_INSTALL_DIR: "/home"
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Root access
      run: sudo -i
    - name: Restore dependencies
      run: dotnet restore src/CacheInMemory/CacheInMemory.csproj
    - name: Build
      run: dotnet build src/CacheInMemory/CacheInMemory.csproj --no-restore
    - name: Publish
      run: dotnet publish src/CacheInMemory/CacheInMemory.csproj -c Release -o website
