name: .NET

on: [push, pull_request]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: sudo dotnet restore src/CacheInMemory/CacheInMemory.csproj
    - name: Build
      run: sudo dotnet build src/CacheInMemory/CacheInMemory.csproj --no-restore
    - name: Publish
      run: sudo dotnet publish src/CacheInMemory/CacheInMemory.csproj -c Release -o website
